### ISSUE TITLE
div class fit-vids-style inserted into head

### ISSUE THREAD

**Issue by AJ-Acevedo** [FameThemes/onepress#237]
I just noticed that a below `div` gets inserted into the head. I verified this on two separate installations with all third party plugins deactivated.

OnePress version 1.4.3
Version version 4.8.1

```css
<div class="fit-vids-style">
  "&shy;"
  <style>
    .fluid-width-video-wrapper {
      width: 100%;
      position: relative;
      padding: 0;
    }
    .fluid-width-video-wrapper iframe, .fluid-width-video-wrapper object, .fluid-width-video-wrapper embed {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
  </style>
</div>
```
